"use strict";

// Static directory pages work without a client router or a homepage fallback.
const fs = require("node:fs");
const path = require("node:path");
const root = path.resolve(__dirname, "..");
const config = require("../website/pages.json");
const escapeHtml = value => String(value).replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[character]));

function renderPage(page, { error = false } = {}) {
  const title = page.title === "Bubble Borough" ? page.title : `${page.title} | Bubble Borough`;
  // Publication is deliberately unavailable until real content has been authored
  // and the launch checks in docs/public-website-implementation.md are complete.
  if (page.ready) throw new Error(`Content rendering and launch review required before publishing ${page.path}`);
  return `<!doctype html>
<!-- Generated by scripts/build-website.cjs. Edit website/pages.json and the shared renderer. -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="robots" content="noindex,follow">
  <meta name="color-scheme" content="dark light">
  <title>${escapeHtml(title)}</title>
  ${page.description ? `<meta name="description" content="${escapeHtml(page.description)}">` : ""}
  <meta property="og:title" content="${escapeHtml(title)}">
  <meta property="og:site_name" content="Bubble Borough">
  <meta property="og:type" content="website">
  <meta property="og:url" content="${escapeHtml(config.origin + page.path)}">
  ${page.description ? `<meta property="og:description" content="${escapeHtml(page.description)}">` : ""}
  <link rel="stylesheet" href="/public/website.css">
</head>
<body>
  <a class="skip-link" href="#main">Skip to content</a>
  <header class="site-header">
    <a class="brand" href="/">Bubble Borough</a>
    <nav aria-label="Main navigation"><a class="play-link" href="/play/" data-action="play-header">Play</a></nav>
  </header>
  <main id="main" tabindex="-1">
    <section class="intro" aria-labelledby="page-title">
      <p class="eyebrow">${error ? "404" : "Bubble Borough"}</p>
      <h1 id="page-title">${escapeHtml(page.title)}</h1>
      <p class="status">${error ? "We couldn’t find that page." : "Coming soon."}</p>
      <a class="play-link" href="/play/" data-action="play-main">Play Bubble Borough <span aria-hidden="true">&rarr;</span></a>
    </section>
  </main>
  <footer class="site-footer"><span>&copy; Bubble Borough</span><a href="/">Home</a><a href="/play/" data-action="play-footer">Play</a></footer>
</body>
</html>
`;
}

function buildOutputs(projectRoot = root) {
  const outputs = new Map();
  for (const page of [config.homepage, ...config.pages]) {
    outputs.set(`${page.path.slice(1)}index.html`, renderPage(page));
  }
  const game = fs.readFileSync(path.join(projectRoot, "index.html"), "utf8");
  if (/<base\b/i.test(game)) throw new Error("Review the existing game base URL before generating /play/.");
  // Preserve all existing game markup/scripts. The base keeps HTML references,
  // fetches and resolveAppUrl() pointed at the existing root asset directories.
  const play = game.replace(/<head>/i, `<head>\n  <base href="/">\n  <meta name="robots" content="noindex,follow">\n  <link rel="canonical" href="${config.origin}/play/">`)
    .replace(/<title>[^<]*<\/title>/i, "<title>Play Bubble Borough</title>")
    .replace('href="./public/manifest.webmanifest"', 'href="/public/play.webmanifest"');
  outputs.set("play/index.html", play);
  const manifest = JSON.parse(fs.readFileSync(path.join(projectRoot, "public/manifest.webmanifest"), "utf8"));
  // Explicit identity preserves the original resolved start URL as app identity.
  outputs.set("public/play.webmanifest", JSON.stringify({ ...manifest, id: "/", start_url: "/play/", scope: "/" }, null, 2) + "\n");
  outputs.set("404.html", renderPage({ title: "Page not found", path: "/404.html", ready: false }, { error: true }));
  outputs.set("robots.txt", `User-agent: *\nAllow: /\n\nSitemap: ${config.origin}/sitemap.xml\n`);
  // Root remains the existing live game during preparation. No unfinished page
  // or game alias is advertised for indexing.
  outputs.set("sitemap.xml", `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n  <url><loc>${config.origin}/</loc></url>\n</urlset>\n`);
  return outputs;
}

function build({ check = false } = {}) {
  const outputs = buildOutputs();
  for (const [relative, body] of outputs) {
    const target = path.join(root, relative);
    if (check) {
      if (!fs.existsSync(target) || fs.readFileSync(target, "utf8") !== body) throw new Error(`${relative} is stale. Run npm run build:website.`);
    } else {
      fs.mkdirSync(path.dirname(target), { recursive: true });
      fs.writeFileSync(target, body);
    }
  }
  console.log(`Website ${check ? "checked" : "prepared"}: ${outputs.size} files; root game unchanged.`);
}

if (require.main === module) build({ check: process.argv.includes("--check") });
module.exports = { build, buildOutputs, renderPage };
